### ISSUE TITLE
Weird toggle delete/create issue

### ISSUE THREAD

**Issue by jebarpg** [Gerrit0/typedoc-plugin-coverage#10]
when I run the command 

`bun typedoc --validation.notDocumented --plugin typedoc-plugin-coverage`

Multiple times it creates the coverage.svg the first time, but then deletes it the second time without creating a new one, then if I run it a third time it creates coverage.svg again.

**Comment by Gerrit0** [comment]
Are you able to reproduce with `node`? This plugin doesn't do anything special with deleting the files:

https://github.com/Gerrit0/typedoc-plugin-coverage/blob/62b95fd8b5213f0d6692bb3c9611d8272cad385b/index.ts#L228

**Comment by jebarpg** [comment]
hmm.. actually when I do 

`bunx typedoc --validation.notDocumented --plugin typedoc-plugin-coverage`

it works no issue.
