### ISSUE TITLE
Suggestion: Customizable label text

### ISSUE THREAD

**Issue by toebeann** [Gerrit0/typedoc-plugin-coverage#4]
It would be quite nice to have a configuration option to customize the text of the badge ("document"), so that instead of:

![image](https://user-images.githubusercontent.com/45315526/185895380-e0411404-88cb-4356-8168-c988209b8458.png) <sub>(generated by your plugin)</sub>

I could get something like:

![image](https://img.shields.io/badge/docs%20coverage-80%25-yellow.svg) <sub>(generated with [shields.io](https://shields.io))</sub>

**Comment by Gerrit0** [comment]
PR welcome, should be pretty easy :)
