### ISSUE TITLE
Support for output custom path

### ISSUE THREAD

**Issue by SalahAdDin** [Gerrit0/typedoc-plugin-coverage#6]
This plugin generates a coverage SVG file and it is pretty cool, but it is not compatible with the [`typedoc-plugin-markdown`](https://github.com/tgreyuk/typedoc-plugin-markdown): When generating the file, it is not referenced by the produced markdown files.

To fix this I opened an [issue](https://github.com/tgreyuk/typedoc-plugin-markdown/issues/573), and I got this [answer](https://github.com/tgreyuk/typedoc-plugin-markdown/issues/573#issuecomment-1933815215): 
> Because the coverage-plugin doesn't currently let you configure the path, you need to copy the badge to your static directory and then you can reference it using a hook with a custom plugin.
> 
> I have added an example stackblitz of this being done:
> 
> https://stackblitz.com/~/github.com/tgreyuk/docusaurus-plugin-typedoc-example
> 
> This is the code for the custom plugin:
> 
> https://github.com/tgreyuk/docusaurus-plugin-typedoc-example/blob/main/docs-website/typedoc-copy-coverage.mjs
> 
> You just reference it in the plugins option like this:
> 
> ```
> plugin: ["typedoc-plugin-coverage", "./typedoc-copy-coverage.mjs"],
> ```

It would be nice to be able to either customize the output path or make this plugin work with [`typedoc-plugin-markdown`](https://github.com/tgreyuk/typedoc-plugin-markdown).

Thanks!

**Comment by tgreyuk** [comment]
@SalahAdDin Just to clarify the coverage plugin does "work" with `typedoc-plugin-markdown`. Its just that in your use-case you need to additionally copy the file to another location. So having a configurable output path would be useful here but not a pre-requisite for integration.

**Comment by SalahAdDin** [comment]
> @SalahAdDin Just to clarify the coverage plugin does "work" with `typedoc-plugin-markdown`. It's just that in your use case you need to additionally copy the file to another location. So having a configurable output path would be useful here but not a pre-requisite for integration.

Yeah, it is not a prerequisite, but it would help to make the integration easier.

**Comment by Gerrit0** [comment]
Seems reasonable, added `coverageOutputPath` in 3.1.0

**Comment by SalahAdDin** [comment]
> Seems reasonable, added `coverageOutputPath` in 3.1.0

It works pretty well, thanks!
