### ISSUE TITLE
Feature request: option for coverage.json

### ISSUE THREAD

**Issue by bladerunner2020** [Gerrit0/typedoc-plugin-coverage#7]
**Summary**
I suggest to add an option that generates coverage.json file along with the coverage.svg badge.

**Motivation**
I want to include a check in our CI/CD pipeline to ensure that the coverage is above a certain threshold (e.g. 80%), similar to how SonarQube checks the test coverage.

**Comment by Gerrit0** [comment]
Sounds like a good idea to me!

**Comment by bladerunner2020** [comment]
I will try to look into it deeply over the weekend and hopefully will submit a PR.

**Comment by Gerrit0** [comment]
Released in 3.2.0
